[project]
timeout = 30
subdir = "xv6-riscv"

[[tests]]
name = "01"
input = ["python3", "runxv6.py", "memtest m 0 3000 A0 p s c 4096"]
expected = """
$ memtest m 0 3000 A0 p s c 4096
[USED] name = A0 boff = 0 bhsz = 32 bsz = 3032 doff = 32 dsz = 3000
[FREE] name = NONE boff = 3032 bhsz = 32 bsz = 1064 doff = 3064 dsz = 1032
malloc_summary():
used  : 3000
free  : 1032
over  : 64
u+f+o : 4096
total : 4096
mem_check() passed with heap <= 4096
"""
rubric = 10

[[tests]]
name = "02"
input = ["python3", "runxv6.py", "memtest m 0 3000 A0 m 1 1000 A1 p s c 4096"]
expected = """
$ memtest m 0 3000 A0 m 1 1000 A1 p s c 4096
[USED] name = A0 boff = 0 bhsz = 32 bsz = 3032 doff = 32 dsz = 3000
[USED] name = A1 boff = 3032 bhsz = 32 bsz = 1064 doff = 3064 dsz = 1032
malloc_summary():
used  : 4032
free  : 0
over  : 64
u+f+o : 4096
total : 4096
mem_check() passed with heap <= 4096
"""
rubric = 10

[[tests]]
name = "03"
input = ["python3", "runxv6.py", "memtest m 0 2000 A0 m 1 1000 A1 m 2 500 A2 p s c 4096"]
expected = """
$ memtest m 0 2000 A0 m 1 1000 A1 m 2 500 A2 p s c 4096
[USED] name = A0 boff = 0 bhsz = 32 bsz = 2032 doff = 32 dsz = 2000
[USED] name = A1 boff = 2032 bhsz = 32 bsz = 1032 doff = 2064 dsz = 1000
[USED] name = A2 boff = 3064 bhsz = 32 bsz = 532 doff = 3096 dsz = 500
[FREE] name = NONE boff = 3596 bhsz = 32 bsz = 500 doff = 3628 dsz = 468
malloc_summary():
used  : 3500
free  : 468
over  : 128
u+f+o : 4096
total : 4096
mem_check() passed with heap <= 4096
"""
rubric = 10

[[tests]]
name = "04"
input = ["python3", "runxv6.py", "memtest m 0 500 A0 m 1 500 A1 m 2 500 A2 m 3 500 A3 f 2 p s c 4096"]
expected = """
$ memtest m 0 500 A0 m 1 500 A1 m 2 500 A2 m 3 500 A3 f 2 p s c 4096
[USED] name = A0 boff = 0 bhsz = 32 bsz = 532 doff = 32 dsz = 500
[USED] name = A1 boff = 532 bhsz = 32 bsz = 532 doff = 564 dsz = 500
[FREE] name = NONE boff = 1064 bhsz = 32 bsz = 532 doff = 1096 dsz = 500
[USED] name = A3 boff = 1596 bhsz = 32 bsz = 532 doff = 1628 dsz = 500
[FREE] name = NONE boff = 2128 bhsz = 32 bsz = 1968 doff = 2160 dsz = 1936
malloc_summary():
used  : 1500
free  : 2436
over  : 160
u+f+o : 4096
total : 4096
mem_check() passed with heap <= 4096
"""
rubric = 10
